name: Cache Demo

on:
  push:
    branches: [ main ]  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Cache dependencies
      - name: prime-cache-2982767
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-dependencies   # Folder to cache
          key: cache-2982767
          restore-keys: cache-2982767

      # Step 3: Echo cache hit/miss
      - name: Show cache result
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
