name: Cache Demo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prime-cache-2982767
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-dependencies
          key: cache-2982767

      - name: Populate cache
        run: |
          mkdir -p ~/.cache/my-dependencies
          echo "Hello world" > ~/.cache/my-dependencies/test.txt

      - name: Show cache result
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
